name: build

on:
  pull_request:

jobs:
  build:
    name: Build and Tests
    runs-on: ${{ matrix.os }}
    env:
      GOPROXY: https://proxy.golang.org
      ARCHIVE_OUTDIR: dist/archives
      TEST_OUTPUT_FILE_PREFIX: test_report
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: [ oldstable, stable ]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run make test
        env:
          COVERAGE_OPTS: "-coverprofile=coverage.txt -covermode=atomic"
        run: make test
      - name: Run make build
        run: make build

