name: lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GOVER: oldstable
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVER }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCILINT_VER }}

